base_model: /storage/models/MBB/base_400M_256
model_name: phase_0_400M_4k
n_layer: 64
d_model: 1024
chunk_size: 4096
batch_size: 3
gradient_accumulation_steps: 1
max_grad_norm: 0.1
max_steps: -1
num_train_epochs: 1
logging_steps: 25
warmup_steps: 300
save_steps: 1500
save_total_limit: 15
learning_rate: 0.0005
